# Generated by Django 2.0.3 on 2018-03-30 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('tweet_date', models.DateField()),
                ('tweet_text', models.TextField()),
                ('article_link', models.URLField()),
                ('title', models.TextField()),
                ('published_date', models.DateField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=100)),
                ('topic_id', models.IntegerField(default=0)),
                ('credibility_score', models.DecimalField(decimal_places=4, default=Decimal('0.7'), max_digits=20)),
            ],
        ),
    ]
