# Generated by Django 2.0.3 on 2018-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('tweet_created_date', models.DateField()),
                ('published_date', models.DateField()),
                ('tweet_text', models.TextField()),
                ('external_link', models.URLField()),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
            ],
        ),
    ]
